{
    'name': 'Agriculture Management',
    'version': '16.0.2.0.0',
    'summary': 'Agriculture Management for Pragati Group',
    'sequence': 4,
    'description': """Agriculture Management module connects to the inventory""",
    'category': 'Productivity',
    'author': 'Root2cloud Solutions',
    'company': 'Root2cloud Solutions',
    'maintainer': 'Root2cloud Solutions',
    'license': 'LGPL-3',
    'depends': [
        'base', 'stock', 'l10n_in'],
    
    'data': [
        'security/user_groups.xml',
        'security/ir.model.access.csv',
        'data/data_sequence.xml',
        'data/crop_cron.xml',
        'wizard/cancel_crop_views.xml',
        'views/menu_action.xml',
        'views/menu_items.xml',
        'views/pest_request.xml',
        'views/damage_loss.xml',
        'views/crop_request.xml',
        'views/crop_line_views.xml',
        'views/disease_details_views.xml',
        'views/menure_request.xml',
        'views/stock_location_views.xml',
        'views/product_template_views.xml',
        'views/crop_planning_views.xml',
        'report/agriculture_report.xml',

    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
