{
    'name': 'Pragati Custom Module',
    'version': '16.0.2.0.0',
    'summary': 'Agriculture Management for Pragati Group',
    'sequence': 4,
    'description': """Agriculture Management module connects to the inventory""",
    'category': 'Productivity',
    'author': 'Root2cloud Solutions',
    'company': 'Root2cloud Solutions',
    'maintainer': 'Root2cloud Solutions',
    'license': 'LGPL-3',
    'depends': [
        'base', 'sale', 'hr', 'stock', 'product', 'approvals', 'purchase', 'website_sale', 'purchase_requisition',
        'service', 'l10n_in', 'material_and_pr_requistion', 'bfa_and_pa_requests', 'mrp', 'gft_inter_account',
        'point_of_sale'
    ],
    'data': [
        'security/ir.model.access.csv',
        'views/account_invoice_report_views.xml',
        'views/menu_action.xml',
        'views/menu_items.xml',
        'data/approval_data_pragati.xml',
        'data/data_sequence.xml',
        'data/stock_alert.xml',
        'views/approval_request_views.xml',
        'views/contact_inherit_views.xml',
        'views/ledger_payment_views.xml',
        'views/account_move_views.xml',
        'views/purchase_order_views.xml',
        'views/sale_order_line_views.xml',
        'views/stock_picking_views.xml',
        'views/delivery_terms_views.xml',
        'views/website_sale_template.xml',
        'views/transfer.xml',
        'views/hand.xml',
        'views/mrp_production.xml',
        'views/department.xml',
        'views/hide.xml',
        'views/PR.xml',
        'views/menu.xml',
        'views/po.xml',
        'views/cp_delay_days.xml',
        'views/pos.xml',
        'views/purchase_report.xml',
        'views/pos_note.xml',
        'views/invisible_date.xml',
        'views/account_test.xml',
        'views/account_balance.xml',
        'views/Inventory_quant.xml',
        'views/custom_stock_move_views.xml',
        'views/pos_invoice_num.xml',
        'views/pos_invoice.xml',
        # 'views/website_js_sale.xml',
        'views/Inventory_stock.xml',
        'views/product_template_views.xml',
        'views/label_printing_report.xml',
        'views/location.xml',
        'views/vendor.xml',
        'views/location_id.xml',
        'views/accounting_invoice.xml',
        'views/mobile.xml',
        'views/manufacturing_order_views.xml',
        'views/pos_order_views.xml',
        'wizard/product_pr_wizard_views.xml',
        # 'report/payment_advise_report.xml',
        'report/delivery_slip_report.xml',
        'report/sale_order_report.xml',
        'report/mrn_date_inhertited_report.xml',
        'report/advance_payments_hms.xml',
        'report/bank_payment_report.xml',
        'report/stockpicking_operations.xml',
        'views/purchase_analysis_views.xml',
        'report/purchase_order_report.xml',
        'report/pos_report.xml',
        'report/label_printing.xml',

    ],
    # 'js': [
    # 'static/src/js/website_sale_custom.js',
    # ],

    # 'assets': {
    #     'web.assets_frontend': [
    #         'static/src/js/website_sale_custom.js',
    #     ],
    # },
    'installable': True,
    'application': True,
    'auto_install': False,
}
